### ISSUE TITLE
How to get user token for apple music?

### ISSUE THREAD

**Issue by deveshb-am** [Lomray-Software/react-native-apple-music#6]
I am using Auth.authorize() function but it only gives me status instead of giving me the user token, is there a way to get the token?

**Comment by Pashkagreen** [comment]
> I am using Auth.authorize() function but it only gives me status instead of giving me the user token, is there a way to get the token?

Hi @deveshb-am, in order to use Apple MusicKit inside of your application, you have to enable MusicKit usage for your application in Apple Developer portal

<img width="708" alt="Screenshot 2024-03-02 at 17 04 25" src="https://github.com/Lomray-Software/react-native-apple-music/assets/91741628/7da3dd67-08f3-419a-af76-1b59976fc4d0">

Please refer to official docs: https://developer.apple.com/documentation/musickit/using-automatic-token-generation-for-apple-music-api

Auth.authorize() will return you only a status, not a token. After you enable usage of MusicKit for your app and successfully authorizes (it means that your user has an AppleMusic application and active subscription on his device), you will be able to use all capabilities of AppleMusic & play music directly in your application. If you have any questions, let me know.

**Comment by Pashkagreen** [comment]
> I am using Auth.authorize() function but it only gives me status instead of giving me the user token, is there a way to get the token?

There is an alternative way to communicate with Apple Music services via bearer token, but it mostly used for web applications. In this case, you will have to create a special service key in Apple developer portal, and then convert it on your node.js server in a bearer token. After that, you can start use it with https://developer.apple.com/documentation/musickitjs/adding_musickit_features_using_html

<img width="523" alt="Screenshot 2024-03-02 at 17 26 02" src="https://github.com/Lomray-Software/react-native-apple-music/assets/91741628/195f31a3-7cf5-4f6f-9e56-b5b4019d4e4c">
